# Creating a sample EKS Cluster configuration

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1

nodeGroups:
  - name: node-group-1
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 5