AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation template to create IAM Roles for ECS Fargate.

Resources:

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: 
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Policies:
        - 
         PolicyName: AmazonECSTaskExecutionRolePolicy
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
              - 
                Effect: "Allow"
                Action: 
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: "*"

Outputs:
  ECSTaskEcecutionRole:
    Description: ECS Task Execution Role Output
    Value: !GetAtt 'ECSTaskExecutionRole.Arn'               
    Export:
      Name: 'ECSTaskExecutionRole'