AWSTemplateFormatVersion: 2010-09-09 
Description: ---
Metadata: 

Parameters: 

Mappings: 

Conditions: 

Resources: 
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: --.--.--.--/--
      EnableDnsSupport: true
      Tags:
        - Key: keyname
          Value: value

Outputs: